### PR TITLE
Add ability to use fog block_device_mapping_v2 on server create

### PR DESCRIPTION
**Pull request by dmlb2000**
This allows full access to create block devices using the block_device_mapping_v2 mechanisms provided by fog.

This allows for setting up things like cinder volume boot and such.

### CODE REVIEW

**Comment by dmlb2000** [comment]
Looks like travis-ci had a bundler issue, has nothing to do with the code I added...

**Comment by jjasghar** [comment]
Awesome. I'll put this on TODO to verify soon

**Comment by dmlb2000** [comment]
This allows one to cinder volume boot a node.

**Comment by karcaw** [comment]
+1 on needing this...  also the Travis CI build seems broken.

**Comment by jjasghar** [comment]
Lovely, gem deps.

I'll get master updated with the newer gems then ask @dmlb2000 to rebase. This should be done this week. Ideally done by 2016-07-28.

**Comment by jjasghar** [comment]
@dmlb2000 if you can rebase off master, https://github.com/chef/knife-openstack/pull/189 fixes travis.

**Comment by tas50** [comment]
Closing this out since we never heard back on the rebase

**Pull request closed without merging**
