### PR TITLE
Allow users to specify alternate private networks.

### PR DESCRIPTION
**Pull request by elbandito**
https://github.com/chef/knife-openstack/issues/146

### CODE REVIEW

**Comment by jjasghar** [comment]
This is great. Can you add some documentation in the README.md about this? It's great to have the comment in the code, but i think people'll want to know that it's an option in their knife.rb.

**Comment by elbandito** [comment]
Sure, thing!  I'll write something up for tomorrow.

**Comment by elbandito** [comment]
@jjasghar added some info to the README.md.  Let me know if it makes sense.

**Comment by jjasghar** [comment]
cool, let me run it through some testing tomorrow, and i'll spend some time setting up a release here in the next few days.

**Comment by jjasghar** [comment]
Will be merged in via: https://github.com/chef/knife-openstack/pull/165/

**Comment by elbandito** [comment]
:+1:

**Pull request merged**
