### PR TITLE
Fix rspec tests for travis CI

### PR DESCRIPTION
**Pull request by PierreRambaud**
HI,

Just a quick fix for travis.
Add rake in Gemfile, remove one useless assignment and fix "set openstack_floating_ip on openstack_floating_ip option" test.

Regards

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Gentle ping!

**Comment by cmluciano** [comment]
Looking through this locally. I think that we should be good to go on rake already since it is defined in the [gemspec](https://github.com/chef/knife-openstack/blob/master/knife-openstack.gemspec#L26). If it is added in the Gemfile, you will get warnings like this 

```
Your Gemfile lists the gem rake (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
```

**Comment by smurawski** [comment]
@jjasghar or @mattray Looks benign enough.. good to merge?

**Comment by lamont-granquist** [comment]
Without knowing the code it LGTM

**Comment by PierreRambaud** [comment]
Using "knife-windows" on branch master make bundle install command failed, other gems are downloaded from rubygems.org, so I remove the "git" symbol.

**Comment by jjasghar** [comment]
I'll be looking at this asap, this is on my radar for today/tomorrow.

**Comment by jjasghar** [comment]
Thanks!

**Pull request merged**
