### PR TITLE
Set the openstack ohai hint when creating a server

### PR DESCRIPTION
**Pull request by mtougeron**

### CODE REVIEW

**Comment by jjasghar** [comment]
:+1:

**Comment by jjasghar** [comment]
TODO: merge into the 1.3.0 release.

**Comment by mtougeron** [comment]
Woohoo! Thanks. :)

**Comment by jjasghar** [comment]
I havent forgotten about this, i'm just waiting on the floating_ip stuff to be done then i'll push a new gem.

**Pull request merged**
