### PR TITLE
1.2.0

### PR DESCRIPTION
**Pull request by jjasghar**
Release of 1.2.0 of the knife-openstack gem.

### CODE REVIEW

**Comment by jjasghar** [comment]
First run with the no new features tested:

```
15:35:34 knife-openstack > (1.2.0) knife openstack server create -N jj-test -I 5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687 -f 101  --openstack-ssh-key-id remasghar01 -a --no-host-key-verify --ssh-user ubuntu

Waiting for server [wait time = 600]...............
Instance ID        a8235380-1031-474f-b0ef-ec57b2f24ded
Name               jj-test                             
Flavor             101                                 
Image              5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687
Keypair            remasghar01                         
State              ACTIVE                              
Availability Zone  az3                                 
Floating IP Address: 15.125.82.165
Bootstrapping the server by using bootstrap_protocol: ssh and image_os_type: linux

Waiting for sshd to host (15.125.82.165)........done
Node jj-test exists, overwrite it? (Y/N) y
Client jj-test exists, overwrite it? (Y/N) y
Creating new client for jj-test
Creating new node for jj-test
Connecting to 15.125.82.165
15.125.82.165 sudo: unable to resolve host jj-test
15.125.82.165 Installing Chef Client...
15.125.82.165 --2015-06-04 20:43:01--  https://www.chef.io/chef/install.sh
15.125.82.165 Resolving www.chef.io (www.chef.io)... 23.235.47.65
15.125.82.165 Connecting to www.chef.io (www.chef.io)|23.235.47.65|:443... connected.
15.125.82.165 HTTP request sent, awaiting response... 200 OK
15.125.82.165 Length: 18716 (18K) [application/x-sh]
15.125.82.165 Saving to: ‘STDOUT’
15.125.82.165 
100%[======================================>] 18,716      --.-K/s   in 0.001s  
15.125.82.165 
15.125.82.165 2015-06-04 20:43:01 (16.0 MB/s) - written to stdout [18716/18716]
15.125.82.165 
15.125.82.165 Downloading Chef 12 for ubuntu...
15.125.82.165 downloading https://www.chef.io/chef/metadata?v=12&prerelease=false&nightlies=false&p=ubuntu&pv=14.10&m=x86_64
15.125.82.165   to file /tmp/install.sh.1585/metadata.txt
15.125.82.165 trying wget...
15.125.82.165 url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.3.0-1_amd64.deb
15.125.82.165 md5	d8421c9b3010deb03e713ada00387e8a
15.125.82.165 sha256	e06eb748e44d0a323f4334aececdf3c2c74d2f97323678ad3a43c33ac32b4f81
15.125.82.165 downloaded metadata file looks valid...
15.125.82.165 downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.3.0-1_amd64.deb
15.125.82.165   to file /tmp/install.sh.1585/chef_12.3.0-1_amd64.deb
15.125.82.165 trying wget...
15.125.82.165 Comparing checksum with sha256sum...
15.125.82.165 Installing Chef 12
15.125.82.165 installing with dpkg...
15.125.82.165 Selecting previously unselected package chef.
(Reading database ... 51689 files and directories currently installed.)
15.125.82.165 Preparing to unpack .../chef_12.3.0-1_amd64.deb ...
15.125.82.165 Unpacking chef (12.3.0-1) ...
15.125.82.165 Setting up chef (12.3.0-1) ...
15.125.82.165 Thank you for installing Chef!
15.125.82.165 Starting first Chef Client run...
15.125.82.165 Starting Chef Client, version 12.3.0
15.125.82.165 resolving cookbooks for run list: []
15.125.82.165 Synchronizing Cookbooks:
15.125.82.165 Compiling Cookbooks...
15.125.82.165 [2015-06-04T20:45:19+00:00] WARN: Node jj-test has an empty run list.
15.125.82.165 Converging 0 resources
15.125.82.165 
15.125.82.165 Running handlers:
15.125.82.165 Running handlers complete
15.125.82.165 Chef Client finished, 0/0 resources updated in 4.650166801 seconds
Instance ID        a8235380-1031-474f-b0ef-ec57b2f24ded
Name               jj-test                             
Public IP          15.125.82.165                       
Flavor             101                                 
Image              5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687
Keypair            remasghar01                         
State              ACTIVE                              
Availability Zone  az3                                 
15:45:40 knife-openstack > (1.2.0) knife openstack server list
Name     Instance ID                           Public IP  Private IP  Flavor  Image                                 Keypair      State   Availability Zone
jj-test  a8235380-1031-474f-b0ef-ec57b2f24ded                         101     5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687  remasghar01  ACTIVE  az3              
15:47:03 knife-openstack > (1.2.0) knife openstack server delete jj-test -y
Instance Name: jj-test
Instance ID: a8235380-1031-474f-b0ef-ec57b2f24ded

WARNING: Corresponding node and client for the jj-test server were not deleted and remain registered with the Chef Server 
```

**Comment by jjasghar** [comment]
@karcaw i tried adding adding a volume to a bootstrap:
```
15:48:37 knife-openstack > (1.2.0) knife openstack server create -N jj-test -I 5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687 -f 101  --openstack-ssh-key-id remasghar01 -a --no-host-key-verify --openstack-volumes aoeu --ssh-user ubuntu
/Users/jasghar/repo/knife-openstack/lib/chef/knife/cloud/openstack_server_create_options.rb:28:in `block (2 levels) in included': undefined local variable or method `openstack_volumes' for Chef::Knife::Cloud::OpenstackServerCreate:Class (NameError)
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:235:in `call'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:235:in `block (3 levels) in opt_parser'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `call'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1454:in `parse!'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:319:in `parse_options'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:299:in `initialize'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/server/create_command.rb:28:in `initialize'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:212:in `new'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:212:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/application/knife.rb:138:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/bin/knife:25:in `<top (required)>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/knife:23:in `load'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/knife:23:in `<main>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
15:49:29 knife-openstack > (1.2.0) 
```

The listing though worked fine.

**Comment by jjasghar** [comment]
Ahh it needs the UUID, i should learn to read. testing again.

**Comment by jjasghar** [comment]
:crying_cat_face: 

```
15:51:51 knife-openstack > (1.2.0) knife openstack volume list
Name  ID                                    Status     Size    Description
aoeu  14e8fcdc-051f-47a9-98ff-02384af7779b  available  100 GB             
15:58:51 knife-openstack > (1.2.0) knife openstack server create -N jj-test -I 5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687 -f 101  --openstack-ssh-key-id remasghar01 -a --no-host-key-verify --openstack-volumes 14e8fcdc-051f-47a9-98ff-02384af7779b  --ssh-user ubuntu
/Users/jasghar/repo/knife-openstack/lib/chef/knife/cloud/openstack_server_create_options.rb:28:in `block (2 levels) in included': undefined local variable or method `openstack_volumes' for Chef::Knife::Cloud::OpenstackServerCreate:Class (NameError)
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:235:in `call'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:235:in `block (3 levels) in opt_parser'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `call'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
	from /Users/jasghar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1454:in `parse!'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:319:in `parse_options'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:299:in `initialize'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/server/create_command.rb:28:in `initialize'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:212:in `new'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/knife.rb:212:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/lib/chef/application/knife.rb:138:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/gems/chef-12.1.1/bin/knife:25:in `<top (required)>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/knife:23:in `load'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/knife:23:in `<main>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
16:00:02 knife-openstack > (1.2.0) 
```

**Comment by karcaw** [comment]
Hmm..  I'll look into it.

**Comment by jjasghar** [comment]
@karcaw no worries! I got it fixed, i'll be pushing it up in a sec.

**Comment by jjasghar** [comment]
Ok, we're good. I'll release the prerelease gem after pushing up the changes and CHANGELOG and what not. Announce it, give it a "week" then push to master.

```

17:44:46 knife-openstack > (1.2.0) bundle exec knife openstack volume list
Name  ID                                    Status     Size    Description
aoeu  14e8fcdc-051f-47a9-98ff-02384af7779b  available  100 GB             
ueoa    available  200 GB             
17:44:57 knife-openstack > (1.2.0) bundle exec knife openstack server create -N jj-test -I 5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687 -f 101  --openstack-ssh-key-id remasghar01 -a --no-host-key-verify --openstack-volumes 14e8fcdc-051f-47a9-98ff-02384af7779b,5c3421cf-96ca-4bf0-8e59-ba3ffcc4ddee  --ssh-user ubuntu

Waiting for server [wait time = 600]..............
Instance ID        f20f02b1-4617-4c7a-9f31-ac9d08131e69
Name               jj-test                             
Flavor             101                                 
Image              5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687
Keypair            remasghar01                         
State              ACTIVE                              
Availability Zone  az3                                 
Floating IP Address: 15.125.82.165
Bootstrapping the server by using bootstrap_protocol: ssh and image_os_type: linux

Waiting for sshd to host (15.125.82.165).........done
Node jj-test exists, overwrite it? (Y/N) y
Client jj-test exists, overwrite it? (Y/N) y
Creating new client for jj-test
Creating new node for jj-test
Connecting to 15.125.82.165
15.125.82.165 sudo: unable to resolve host jj-test
15.125.82.165 Installing Chef Client...
15.125.82.165 --2015-06-04 22:49:15--  https://www.opscode.com/chef/install.sh
15.125.82.165 Resolving www.opscode.com (www.opscode.com)... 166.78.227.233
15.125.82.165 Connecting to www.opscode.com (www.opscode.com)|166.78.227.233|:443... connected.
15.125.82.165 HTTP request sent, awaiting response... 200 OK
15.125.82.165 Length: 18736 (18K) [application/x-sh]
15.125.82.165 Saving to: ‘STDOUT’
15.125.82.165 
100%[======================================>] 18,736      --.-K/s   in 0.002s  
15.125.82.165 
15.125.82.165 2015-06-04 22:49:15 (9.99 MB/s) - written to stdout [18736/18736]
15.125.82.165 
15.125.82.165 Downloading Chef 12 for ubuntu...
15.125.82.165 downloading https://www.opscode.com/chef/metadata?v=12&prerelease=false&nightlies=false&p=ubuntu&pv=14.10&m=x86_64
15.125.82.165   to file /tmp/install.sh.1586/metadata.txt
15.125.82.165 trying wget...
15.125.82.165 url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.3.0-1_amd64.deb
15.125.82.165 md5	d8421c9b3010deb03e713ada00387e8a
15.125.82.165 sha256	e06eb748e44d0a323f4334aececdf3c2c74d2f97323678ad3a43c33ac32b4f81
15.125.82.165 downloaded metadata file looks valid...
15.125.82.165 downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.3.0-1_amd64.deb
15.125.82.165   to file /tmp/install.sh.1586/chef_12.3.0-1_amd64.deb
15.125.82.165 trying wget...
15.125.82.165 Comparing checksum with sha256sum...
15.125.82.165 Installing Chef 12
15.125.82.165 installing with dpkg...
15.125.82.165 Selecting previously unselected package chef.
(Reading database ... 51689 files and directories currently installed.)
15.125.82.165 Preparing to unpack .../chef_12.3.0-1_amd64.deb ...
15.125.82.165 Unpacking chef (12.3.0-1) ...
15.125.82.165 Setting up chef (12.3.0-1) ...
15.125.82.165 Thank you for installing Chef!
15.125.82.165 Starting first Chef Client run...
15.125.82.165 Starting Chef Client, version 12.3.0
15.125.82.165 resolving cookbooks for run list: []
15.125.82.165 Synchronizing Cookbooks:
15.125.82.165 Compiling Cookbooks...
15.125.82.165 [2015-06-04T22:50:05+00:00] WARN: Node jj-test has an empty run list.
15.125.82.165 Converging 0 resources
15.125.82.165 
15.125.82.165 Running handlers:
15.125.82.165 Running handlers complete
15.125.82.165 Chef Client finished, 0/0 resources updated in 4.724917734 seconds
Instance ID        f20f02b1-4617-4c7a-9f31-ac9d08131e69
Name               jj-test                             
Public IP          15.125.82.165                       
Flavor             101                                 
Image              5f3c18e7-d0eb-4440-ac37-0cf6d6d2b687
Keypair            remasghar01                         
State              ACTIVE                              
Availability Zone  az3                                 
17:50:50 knife-openstack > (1.2.0) ssh ubuntu@15.125.82.165
The authenticity of host '15.125.82.165 (15.125.82.165)' can't be established.
RSA key fingerprint is 49:04:2d:d1:fe:7f:49:d8:bc:bd:a4:a2:eb:5e:73:7f.
Are you sure you want to continue connecting (yes/no)? yes

Warning: Permanently added '15.125.82.165' (RSA) to the list of known hosts.
Welcome to Ubuntu 14.10 (GNU/Linux 3.16.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu Jun  4 22:50:32 UTC 2015

  System load:  0.52              Processes:           89
  Usage of /:   3.2% of 29.39GB   Users logged in:     0
  Memory usage: 6%                IP address for eth0: 10.0.0.26
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

New release '15.04' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Thu Jun  4 22:49:14 2015 from cpe-173-174-100-178.austin.res.rr.com
]0;ubuntu@jj-test: ~ubuntu@jj-test:~$ sudo fdisk -l
sudo: unable to resolve host jj-test

Disk /dev/vda: 30 GiB, 32212254720 bytes, 62914560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: D851FF40-A1F7-44AA-84BD-BDCD746725CF

Device      Start      End  Sectors  Size Type
/dev/vda1  227328 62914526 62687199 29.9G Linux filesystem
/dev/vda14   2048    10239     8192    4M BIOS boot
/dev/vda15  10240   227327   217088  106M EFI System

Partition table entries are not in disk order.
Disk /dev/vdb: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/vdc: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/vdd: 200 GiB, 214748364800 bytes, 419430400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
]0;ubuntu@jj-test: ~ubuntu@jj-test:~$ ```

**Comment by karcaw** [comment]
Great!

**Comment by jjasghar** [comment]
I should make it clear, it wasn't actually me, it was @adamleff. :metal:

**Comment by jjasghar** [comment]
I should try to get this https://github.com/chef/knife-openstack/issues/161 resolved with this release too.

**Comment by adamleff** [comment]
Yay teamwork! :metal: Happy to help anytime.

**Comment by jjasghar** [comment]
On hold till the knife-cloud 1.1.1 is pushed to rubygems.

**Comment by jjasghar** [comment]
RC released of knife-cloud, pushing new RC release of this now.

**Pull request merged**
