### PR TITLE
1.1.0 release branch

### PR DESCRIPTION
**Pull request by jjasghar**
This should be what's required to prep for 1.1.0 release of knife-openstack.

### CODE REVIEW

**Comment by jjasghar** [comment]
Looks like a ruby gem dependancy hell:
```shell
11:29:15 knife-openstack > (1.1.0) bundle install
Updating https://github.com/opscode/knife-windows.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "winrm":
  In Gemfile:
    knife-windows (>= 0) ruby depends on
      winrm-s (~> 0.2) ruby depends on
        winrm (~> 1.2.0) ruby

    knife-windows (>= 0) ruby depends on
      winrm (1.3.0)
11:29:25 knife-openstack > (1.1.0)
```

**Comment by mattray** [comment]
This is fine, I'll go look at the patches going into 1.1.0.

**Comment by jjasghar** [comment]
Running into an issue now with the update

```ruby
12:52:05 knife-openstack > (1.1.0) knife openstack server list -VV
INFO: Using configuration from /Users/jasghar/.chef/knife.rb
DEBUG: openstack_username jjasghar
DEBUG: openstack_auth_url https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/tokens
DEBUG: openstack_tenant 10917180154984-Project
DEBUG: openstack_endpoint_type publicURL
DEBUG: openstack_insecure
DEBUG: Using fog version: 1.28.0
/Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/fog-1.28.0/lib/fog/openstack/core.rb:149:in `authenticate_v2': Multiple regions available choose one of these 'region-a.geo-1,region-b.geo-1' (Fog::Errors::NotFound)
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/fog-1.28.0/lib/fog/openstack/compute.rb:395:in `authenticate'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/fog-1.28.0/lib/fog/openstack/compute.rb:320:in `initialize'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/fog-core-1.29.0/lib/fog/core/service.rb:115:in `new'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/fog-core-1.29.0/lib/fog/core/service.rb:115:in `new'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/fog-core-1.29.0/lib/fog/compute.rb:64:in `new'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/fog/service.rb:35:in `connection'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/fog/service.rb:120:in `block (2 levels) in <class:FogService>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/server/list_command.rb:65:in `query_resource'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/list_resource_command.rb:35:in `execute_command'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/chef-12.1.0/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/chef-12.1.0/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/chef-12.1.0/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/chef-12.1.0/lib/chef/knife.rb:214:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/chef-12.1.0/lib/chef/application/knife.rb:138:in `run'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/chef-12.1.0/bin/knife:25:in `<top (required)>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/bin/knife:23:in `load'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/bin/knife:23:in `<main>'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/bin/ruby_executable_hooks:15:in `<main>'
12:52:10 knife-openstack > (1.1.0) e ~/.chef/knife.rb
```

**Comment by jjasghar** [comment]
Looks like it's in repo of: https://github.com/chef/knife-openstack/issues/152

**Comment by jjasghar** [comment]
```ruby
[22] pry(#<Hash>):1> self [ :openstack_region ] = "region-a.geo-1"
=> "region-a.geo-1"
[23] pry(#<Hash>):1> self
=> {:provider=>"OpenStack",
 :openstack_username=>"jjasghar",
 :openstack_api_key=>"NOTAREALP@$$W0RD!",
 :openstack_auth_url=>"https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/tokens",
 :openstack_endpoint_type=>nil,
 :openstack_tenant=>"10917180154984-Project",
 :connection_options=>{:ssl_verify_peer=>true},
 :openstack_region=>"region-a.geo-1"}
[24] pry(#<Hash>):1> cd ..
[25] pry(#<Chef::Knife::Cloud::OpenstackService>)> list_servers

From: /Users/jasghar/.rvm/gems/ruby-2.1.1@knife-openstack/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/fog/service.rb @ line 36 Chef::Knife::Cloud::FogService#connection:

    32: def connection
    33:   add_api_endpoint
    34:
    35:   @connection ||= begin
 => 36:                                                                                                 require 'pry'; binding.pry
    37:                     connection  = Fog::Compute.new(@auth_params)
    38:
    39:                   rescue Excon::Errors::Unauthorized => e
    40:                     error_message = "Connection failure, please check your username and password."
    41:                     ui.fatal(error_message)
    42:                     raise CloudExceptions::ServiceConnectionError, "#{e.message}. #{error_message}"
    43:                   rescue Excon::Errors::SocketError => e
    44:                     error_message = "Connection failure, please check your authentication URL."
    45:                     ui.fatal(error_message)
    46:                     raise CloudExceptions::ServiceConnectionError, "#{e.message}. #{error_message}"
    47:                   end
    48:
    49: end

[1] pry(#<Chef::Knife::Cloud::OpenstackService>)> continue
NameError: undefined local variable or method `continue' for #<Chef::Knife::Cloud::OpenstackService:0x00000103866c68>
from (pry):20:in `connection'
[2] pry(#<Chef::Knife::Cloud::OpenstackService>)>
=> []
[26] pry(#<Chef::Knife::Cloud::OpenstackService>)>
```

**Comment by jjasghar** [comment]
```shell
Waiting for sshd to host (15.125.82.165)........done
Creating new client for openstack-5183
Creating new node for openstack-5183
Connecting to 15.125.82.165
FATAL: Authentication Failed during bootstrapping. Authentication failed for user root@15.125.82.165@15.125.82.165.
```

It looks like CRUD is working but that double up FATAL message is annoying.

**Comment by jjasghar** [comment]
It looks like that root@blah@blah is an issue with knife-cloud not knife-openstack.  I'll debug it another time. I think this is pretty much good to go.

**Comment by jjasghar** [comment]
One failing test:
```ruby
Failures:

  1) Chef::Knife::Cloud::OpenstackServerCreate#after_exec_command set openstack_floating_ip on openstack_floating_ip option
     Failure/Error: @instance.after_exec_command
     NoMethodError:
       undefined method `network' for #<Chef::Knife::Cloud::Service:0x000001022daf98 @auth_params=nil>
     # ./lib/chef/knife/openstack_server_create.rb:107:in `after_exec_command'
     # ./spec/unit/openstack_server_create_spec.rb:190:in `block (3 levels) in <top (required)>'

Finished in 0.26827 seconds (files took 0.80038 seconds to load)
94 examples, 1 failure
```

**Comment by jjasghar** [comment]
This test should be relsoved now.

**Comment by cmluciano** [comment]
Worked with @jjasghar on this yesterday and today. I'm a 👍 on this release

**Pull request merged**
