### PR TITLE
Vol sched 1.0.0work

### PR DESCRIPTION
**Pull request by karcaw**
Rework of pull request #135 for the 1.0.0.rc1.

This adds volume list capabilities, and ability to specify volume attachments and add scheduler hints when creating a server.

### CODE REVIEW

**Comment by jjasghar** [comment]
Awesome, this is really great.

Could you add some specs for this too? Also add this to the readme so we can document this change?

**Comment by karcaw** [comment]
I'll work on some documentation

**Comment by karcaw** [comment]
I've added specs, and a small blurb in the readme.

**Comment by jjasghar** [comment]
Will be merged in via: https://github.com/chef/knife-openstack/pull/165/

**Pull request merged**
